// Automatically generated by MockGen. DO NOT EDIT!
// Source: aws/firehose.go

package heka_clever_plugins

import (
	gomock "github.com/rafrombrc/gomock/gomock"
)

// Mock of Firehose interface
type MockFirehose struct {
	ctrl     *gomock.Controller
	recorder *_MockFirehoseRecorder
}

// Recorder for MockFirehose (not exported)
type _MockFirehoseRecorder struct {
	mock *MockFirehose
}

func NewMockFirehose(ctrl *gomock.Controller) *MockFirehose {
	mock := &MockFirehose{ctrl: ctrl}
	mock.recorder = &_MockFirehoseRecorder{mock}
	return mock
}

func (_m *MockFirehose) EXPECT() *_MockFirehoseRecorder {
	return _m.recorder
}

func (_m *MockFirehose) Send(data []byte) error {
	ret := _m.ctrl.Call(_m, "Send", data)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFirehoseRecorder) Send(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Send", arg0)
}
